version: "3.9"

services:
  database:
    image: postgres
    container_name: database_podcastr
    restart: always
    ports:
      - 5532:5532
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=podcastr
    volumes:
      - pgdata:/data/postgres
  app:
      build: .
      container_name: podcastr
      restart: always
      ports:
        - 5432:5432
      volumes:
        - .:/usr/app
      links:
        - database
      depends_on:
        - database

volumes:
  pgdata:
    driver: local




